version: '3.7'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - $PWD:/app
    ports:
      - 8080:8080
  aws:
    image: anigeo/awscli
    environment:
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_REGION: us-west-2
      AWS_DEFAULT_REGION: us-west-2
    volumes:
      - $PWD:/app
    working_dir: /app
    # env_file: .env
  terraform:
    build:
      dockerfile: terraform.Dockerfile
      context: .
    environment:
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_REGION: us-west-2
      AWS_DEFAULT_REGION: us-west-2
    volumes:
      - $PWD:/app
    working_dir: /app
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
  website:
   build:
    context: .
   ports:
    - 80:80
  integration-tests:
    build:
      dockerfile: rspec.dockerfile
      context: .
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - $PWD:/app
    entrypoint: rspec
    command:
      - --pattern
      - /app/spec/integration/*_spec.rb
  unit-tests:
    build:
      dockerfile: rspec.dockerfile
      context: .
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - $PWD:/app
    entrypoint: rspec
    command:
      - --pattern
      - /app/spec/unit/*_spec.rb
